The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [4]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
y = arr.view()
y[0] = 32
print(arr)
print(x)
print(arr)
print(y)
print(x.base, y.base)
# import numpy as np
arr = np.array([1, 2, 3, 4], ndmin = 5)
print(arr)
print('shape of array:', arr.shape)

[32  2  3  4  5]
[1 2 3 4 5]
[32  2  3  4  5]
[32  2  3  4  5]
None [32  2  3  4  5]
[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [40]:
import numpy as np

# arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# for x in np.nditer(arr):
#     print(x)
    
# arr = np.array([1, 2, 3])

# for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
#   print(x)
# print(arr)

# for idx, x in np.ndenumerate(arr):
#     print(idx, x)

# arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# for idx, x in np.ndenumerate(arr):
#     print(idx, x)
    
# arr1 = np.array([1, 2, 3])
# arr2 = np.array([4, 5 ,6])

# arr = np.concatenate((arr1, arr2), axis = 0)
# print(arr)

# arr1 = np.array([[1, 2], [3, 4]])
# arr2 = np.array([[5, 6], [7, 8]])

# arr = np.concatenate((arr1, arr2), axis = 0)
# print(arr)
# for x in arr:
#     print(x)
    # for y in x:
    #     for z in y:
    #         print(z)
    
# arr1 = np.array([1, 2, 3])
# arr2 = np.array([4, 5, 6])

# arr = np.stack((arr1, arr2), axis = 1)
# print(arr.shape)

# arr = np.stack((arr1, arr2), axis = 0)
# print(arr.shape)

# arr1 = np.array([1, 2, 3])
# arr2 = np.array([4, 5, 6])

# arr = np.hstack((arr1, arr2))
# print(arr)
# arr = np.vstack((arr1, arr2))
# print(arr)
# arr = np.dstack((arr1, arr2))
# print(arr)

# arr = np.array([1, 2, 3, 4, 5, 6])

# newarr = np.array_split(arr, 3)

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

# print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis = 1)

# rint(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

# print(x)

arr = np.array([True, False, False])
# print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])

# print(np.sort(arr))

# filter

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)



[False  True False  True False  True False]
[2 4 6]


In [5]:
from numpy import random

# x = random.choice([3, 5, 7, 9])
# x = random.randint(100, size=(5,))
# print(x)
# x = random.rand()

x = random.choice([3, 5, 7, 9], p = [0.1, 0.2, 0.3, 0.4])
print(x)

5


In [10]:
from numpy import rad2deg
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
random.permutation(arr)
x = random.normal(size = (2,3))
print(x)

[[-0.22606332 -1.83596133 -0.1759734 ]
 [ 1.33988591 -0.65435435  0.64284744]]
